config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  get 'pages/dashboard'
  get 'pages/terms'

  resources :motorbikes do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:show] do
    patch '/accept', to: "bookings#accept"
    patch '/reject', to: "bookings#reject"
    resources :reviews, only: [:new, :create]
  end
  devise_for :users
  root to: 'pages#home'
end

app/views/shared/_bookingcard.html.erb
<!-- This is the ........? -->

<%= link_to booking_path(booking), class: "card-product" do %>
  <div class="Card__inner">
    <div class="Card__body">
    <figure class="Card__img">
      <%= cl_image_tag booking.motorbike.photos[0].key %>
    </figure>
      <h4 class="Card__name">Booking id <%= booking.id %></h4>
      <h3 class="Card__name">start date <%= booking.start_date %></h3>
      <h3 class="Card__name">end date <%= booking.end_date %></h3>
      <h3 class="Card__name">Booking status: <%= booking.status %></h3>
    </div>
  </div>
<% end %>

app/views/shared/_card.html.erb
<%= link_to motorbike_path(motorbike), style: "text-decoration: none;" do %>
  <div class="p-2">
    <div class="mobike-card">
        <% if motorbike.photos[0] %>
          <%= cl_image_tag motorbike.photos[0].key, width: 300, height:300, fill: :crop, class: 'lazyload' %>
        <% end %>
      <div class="mobike-card-infos">
        <div class="text-left">
          <h2><%= motorbike.make %> , <%= motorbike.model %></h2>
          <p>Short description here!</p>
        </div>
        <h2 class="mobike-card-pricing" style="color: black;">$ <%= "#{motorbike.price}" %> / day</h2>
        <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="mobike-card-user avatar-bordered" />
      </div>
    </div>
  </div>
<% end %>

<!-- Old code

<#%= link_to motorbike_path(motorbike), class: "Card" do %>
  <div class="Card__inner ">
    <figure class="Card__img">
      <#% if motorbike.photos[0] %>
          <#%= cl_image_tag motorbike.photos[0].key, width: 300, height:300, fill: :crop, class: 'lazyload' %>
      <#% end %>
    </figure>
    <div class="Card__body">
      <h3 class="Card__name"><#%= motorbike.make %> , <%= motorbike.model %></h3>
      <div class="Card__price">$ <#%= "#{motorbike.price}" %> / day</div>

      <div class="Card__meta">
        <div class="Card__rating">
          <#% motorbike.average_rating.times do %>
            <i class="fas fa-star" style="color: #ffb400;"></i>
          <#% end %>
        this line was commented out <i class="fas fa-heart color-grey-text"></i>
        </div>
      </div>
    </div>
  <#% end %>
</div> -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= 'navbar-homepage' if request.path == root_path %>">
  <%= link_to "/", class: "navbar-brand" do %>
<!--     <#%= image_tag "moBikelogoDark.png" %>
 --> <h5 class="px-4" style="font-weight: 700; font-family: 'Oxanium', cursive; display: inline;" class=" justify-content-start">moBike</h5>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if request.path != root_path %>
          <li class="nav-item active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
        <% end %>
          <li class="nav-item">
            <%= link_to "Dashboard", pages_dashboard_path, class: "nav-link" %>
          </li>
        <% if request.path == root_path %>
          <li class="nav-item">
            <%= link_to "List your bike", new_motorbike_path, class: "btn btn-sm btn-outline-white px-3 mx-2" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "List your bike", new_motorbike_path, class: "btn btn-sm btn-outline px-3 mx-2" %>
          </li>
        <% end %>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, width: 40, height: 40, crop: "fill", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false  %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-right <%= 'dropdown-menu-home' if request.path == root_path %>" aria-labelledby="navbarDropdown">
              <%= link_to "Account", "#", class: "dropdown-item" %>
              <%= link_to "Dashboard", pages_dashboard_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
      <% else %>
        <% if request.path == root_path %>
          <li class="nav-item">
            <%= link_to "List your bike", new_motorbike_path, class: "btn btn-sm btn-outline-white px-3 mx-2" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "List your bike", new_motorbike_path, class: "btn btn-sm btn-outline px-3 mx-2" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>