config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  get 'pages/dashboard'
  get 'pages/terms'

  resources :motorbikes do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:show] do
    patch '/accept', to: "bookings#accept"
    patch '/reject', to: "bookings#reject"
    resources :reviews, only: [:new, :create]
  end
  devise_for :users
  root to: 'pages#home'
end

app/views/pages/_motorbike_card.html.erb
<% motorbike.bookings.each do |booking| %>
  <% unless ['accepted', 'rejected'].include? booking.status %>
    <%= link_to "Accept", booking_accept_path(booking), method: :patch %>
    <%= link_to "Reject", booking_reject_path(booking), method: :patch %>
  <% end %>
<% end %>

app/views/pages/dashboard.html.erb
<%# TODO: Fix inline styles  %>
<section style="margin-top: 60px;">
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h3>
        Dashboard
      </h3>
    </div>
  </div>
  <div class="container-fluid">
  <div class="row">
    <div class="col-3">
      <ul class="list-group">
          <li class="list-group-item">
            <%= link_to 'All Bikes', motorbikes_path %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Edit Profile', edit_user_registration_path %>
          </li>
          <li class="list-group-item">
            <%= link_to 'Terms', pages_terms_path  %>
          </li>
          <li class="list-group-item">
            <%= link_to destroy_user_session_path, method: :delete do %>
              Log out
            <% end %>
          </li>
        </ul>
    </div>
    <div class="col-6">
        <div class="bookingcards">
          <div>
            <% @bookings.each do |booking| %>
             <div class="card-dashboard">
              <%= cl_image_tag booking.motorbike.photos[0].key%>

              <div class="card-product-infos">
                <h4><%= booking.motorbike.model %></h4>

              <div class="card-dashboard-infos">
                <h2><%= booking.motorbike.make %></h2>
                <p><%= booking.motorbike.model %></p>
                <p><%= booking.status %></p>
                <p>start date: <%= booking.start_date %>   end date:<%= booking.end_date %></p>
                <% if policy(Review.new(booking: booking)).create? %>
                  <%= link_to 'Add a review', new_booking_review_path(booking)  %>
                <% end %>
              </div>
            </div>
            <% end %>
          </div>
        </div>

        <div class="col-3">
          <% @motorbikes.each do |motorbike| %>
            <%= render "motorbike_card", motorbike: motorbike %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/pages/home.html.erb
<div class="home-banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.8)), url(https://images.unsplash.com/photo-1558980664-769d59546b3d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80);">
  <h1>MoBike brings the<strong> open road</strong> to <strong>you</strong>!</h1>
    <div class="container col-7">
      <%= form_tag motorbikes_path, class: "search-form-control form-group", method: :get do %>
      <%= text_field_tag :query, params[:query], class: "form-control string required", placeholder: "Enter city or make of bike" %>
      <%= submit_tag "Search", class: "btn btn-flat" %>
      <% end %>
      <ul id="dropdown"></ul>
    </div>
  <p id="view-all" style="margin: 0;"><%= link_to "View all bikes", motorbikes_path, class: "btn btn-outline-white ml-2"%></p>
</div>