config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  get 'reviews/create'
  get 'pages/dashboard'
  get 'pages/terms'

  resources :motorbikes do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:show] do
    patch '/accept', to: "bookings#accept"
    patch '/reject', to: "bookings#reject"
    resources :reviews, only: [:new, :create]
  end
  devise_for :users
  root to: 'pages#home'
end

app/models/motorbike.rb
class Motorbike < ApplicationRecord
  CATEGORIES = ['Moped', 'Naked Bike', 'Superbike', 'Cafe Racer', 'Enduro', 'Hard Tail', 'Cruiser', 'Sportbike', 'Custom']
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  belongs_to :user
  has_many_attached :photos

  geocoded_by :address, if: :will_save_change_to_address?
  after_validation :geocode

  validates :make, presence: true
  validates :model, presence: true
  validates :year, presence: true
  validates :description, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  validates :address, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_make_and_model_and_address_and_category,
    against: [ :make, :model, :address, :category ],
    using: {
      tsearch: { prefix: true }
  }

  include AlgoliaSearch

  algoliasearch do
    attributes :make, :model, :address, :category
  end

  def average_rating
    if !reviews.empty?
      reviews.pluck(:rating).sum / reviews.length
    else
      0
    end
  end

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
end

app/controllers/motorbikes_controller.rb
class MotorbikesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_motorbike, only: [:show, :edit, :update, :destroy]

  def index
    #Get all the bikes geocoded
    @motorbikes = policy_scope(Motorbike).geocoded

    if params[:query].present?
        @motorbikes = @motorbikes.search_by_make_and_model_and_address_and_category(params[:query])
    end



    @markers = @motorbikes.map do |motorbike|
      {
        lat: motorbike.latitude,
        lng: motorbike.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { motorbike: motorbike }),
       }
    end
  end

  def show
    @booking = Booking.new
    @reviews = @motorbike.reviews
    authorize @motorbike
    @markers =
      [{
        lat: @motorbike.latitude,
        lng: @motorbike.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { motorbike: @motorbike }),
      }]
  end

  def new
    @motorbike = Motorbike.new
    authorize @motorbike
  end

  def create
    @motorbike = Motorbike.new(motorbike_params)
    @motorbike.user = current_user
    authorize @motorbike
    if @motorbike.save
      redirect_to motorbike_path(@motorbike), notice: 'Your bike was successfully created.'
    else
      render 'new'
    end
  end

  def edit
    authorize @motorbike
  end

  def update
    authorize @motorbike
    if @motorbike.update(motorbike_params)
      redirect_to @motorbike, notice: 'Your bike was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    authorize @motorbike
    @motorbike.destroy
    redirect_to motorbikes_url, notice: 'Your bike was successfully deleted.'
  end

  private

  def set_motorbike
    @motorbike = Motorbike.find(params[:id])
  end

  def motorbike_params
    params.require(:motorbike).permit(:make, :model, :year, :description, :price, :address, :category, photos: [])
  end
end

app/views/motorbikes/_form.html.erb
      <%= simple_form_for(motorbike) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-row">
        <div class="col-md-12">
          <%= f.input :make, placeholder: "Make", label: false  %>
        </div>
        <div class="col-md-6">
          <%= f.input :model, placeholder: "Model", label: false  %>
        </div>
        <div class="col-md-6">
          <%= f.input :year, placeholder: "Year", label: false  %>
        </div>
        </div>
        <div class="form-inputs">
          <%= f.input :description, placeholder: "Description of your bike", label: false  %>
        </div>
        <div class="form-inputs">
          <%= f.input :price, placeholder: "Enter daily rate", label: false  %>
        </div>
        <div class="form-inputs">
          <%= f.input :address, placeholder: "Address", label: false  %>
        </div>
        <div class="form-inputs">
          <%= f.input :category, collection: Motorbike::CATEGORIES, label: false, include_blank: "Select category" %>
        </div>
        <div class="form-inputs text-left">
          <p><strong>Add Photos</strong></p>
          <%= f.input :photos, as: :file, input_html: { multiple: true }, label: false %>
        </div>
          <div class="form-action d-lg-flex d-block">
            <div class="form-actions w-100">
              <%= f.button :submit, class: 'btn-mobike'%>
                <div>
                  <%= link_to "Go back", motorbikes_path, class: 'btn btn-mobike'%>
                </div>
              <div>
            </div>
          </div>
        </div>
      <% end %>
      <div style="height: 80px;"></div>

app/views/motorbikes/_info_window.html.erb
<div class="info">
  <h5><%= motorbike.make %>, <%= motorbike.model %></h5>
  <p><%= motorbike.address %></p>
  <div class="info-image" style="background-image: url(<%= cl_image_path motorbike.photos.first.key %>)"></div>
</div>

app/views/motorbikes/create.html.erb
<h1>Motorbikes#create</h1>
<p>Find me in app/views/motorbikes/create.html.erb</p>

app/views/motorbikes/destroy.html.erb
<h1>Motorbikes#destroy</h1>
<p>Find me in app/views/motorbikes/destroy.html.erb</p>

app/views/motorbikes/edit.html.erb
<h4 style="padding-top: 50px; padding-bottom: 30px;">Edit your motorbike</h4>

<%= render 'form', motorbike: @motorbike  %>

app/views/motorbikes/index.html.erb
<h4 style="padding: 25px; text-align: justify;"><%= @motorbikes.count %> Motorbikes</h4>
<section class="motorbikes">
  <div class="container-fluid">
    <div class="Cards">
      <div class="Cards__grid d-flex">
        <div class="col-md-8">
          <div class="cards">
            <% @motorbikes.each do |motorbike|  %>
             <div class="grid-item">
                 <%= render 'shared/card', motorbike: motorbike %>
             </div>
            <% end %>
          </div>
        </div>
        <div class="col-md-4">
          <div  id="map" style="width: 100%; height: 100vh; position: sticky; top: 0 " data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
    </div>
  </div>
</section>


<div class="col-12">
  <%= link_to "/", class: "endSearch" do %>
  <%= image_tag "mcglass.png", class: "mc-class" %>
  <% end %>
</div>

<h6>No more bike!</h6>
<p>Try changing your filters, adjusting your dates, or exploring the map</p>

app/views/motorbikes/new.html.erb
<div class="container" style="background-color: white; border-radius: 3px; width: 60%; box-shadow: 0px 0px 48px 2px rgba(219,219,219,1);">
  <div class="row">
    <div class="col-md-6 mx-auto">

      <h1 style="padding-top: 50px; padding-bottom: 30px;">Add your bike!</h1>
        <%= render 'form', motorbike: @motorbike  %>

    </div>
  </div>
</div>

app/views/motorbikes/show.html.erb
<div class="container show-container">
  <div class="row justify-content-center align-items-center">
    <div class="col-md-5 col-sm-12">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= cl_image_tag @motorbike.photos[0].key, height: 300, width: 420, crop: :fill, class: "d-block w-100"  %>
          </div>
          <% @motorbike.photos[1..-1].each do |photo| %>
          <div class="carousel-item">
          <%= cl_image_tag photo.key, height: 300, width: 420, crop: :fill, class: "d-block w-100" %>
          </div>
          <% end %>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
    <div class="col-md-4 col-sm-12">
        <h3 class="make-model"><%= @motorbike.make %>, <%= @motorbike.model %></h3>
        <h4><%= @motorbike.year %></h4>
        <p><%= @motorbike.address %></p>
        <p>$<%= @motorbike.price %></p>
        <div style="overflow: auto; width:100%; height:150px;"><p><%= @motorbike.description %></p></div>
    </div>
    <div class="col-md-3 col-sm-12">
      <div id='motorbike-booking-dates' data-unavailable="<%= @motorbike.unavailable_dates.to_json %>">
        <% if current_user && current_user.id != @motorbike.user_id  %>
            <%= simple_form_for([@motorbike, @booking]) do |f| %>
              <%= f.input :start_date,label: 'Booking Start Date', as: :string, type: :text %>
              <%= f.input :end_date, label: 'Booking End Date', as: :string, type: :text %>
              <%= f.submit "Book", id: "show-page-button", class: "btn btn-outline-info ml-2" %>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <br>
  <hr>
</div>

<div class="show_map">
  <div class="col-lg-12 mx-auto">
    <div  id="map" style="width: 85%; height: 30vh; margin-top: 20px; display: inline-block;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

<!-- Below are the Three Buttons on the Show Page -->

<%= link_to "View all bikes", motorbikes_path, id: "show-page-button", class: "btn btn-outline-info ml-2"%>


<% if policy(@motorbike).edit? %>
    <%= link_to "Edit", edit_motorbike_path(@motorbike), id: "show-page-button", class: "btn btn-outline-info ml-2"%>
<% end %>

<% if policy(@motorbike).destroy? %>
    <%= link_to "Delete", motorbike_path(@motorbike), id: "show-page-button", class: "btn btn-outline-info ml-2", method: :delete, data: { confirm: "Are you sure?" }%>
<% end %>


<div class="review_container">
  <h3>See what past riders have to say about this bike!</h3>
  <div class="row" style="width: 60%; margin: 0 auto;">
    <div class="col">
      <% @motorbike.reviews.each do |review| %>
      <h5 style="margin-bottom: 35px;"><%= review.rating %>  <i class="fas fa-star" style="color: rgb(231, 76, 60)"> </i> <%= review.description %></h5>
      <% end %>
    </div>
  </div>
</div>

app/views/motorbikes/update.html.erb
<h1>Motorbikes#update</h1>
<p>Find me in app/views/motorbikes/update.html.erb</p>